version: "2.1"

services:
  postgres:
    image: postgres:10.4
    container_name: technical-test-postgres
    environment:
      - POSTGRES_DB=staycation
      - POSTGRES_USER=staycation
      - POSTGRES_PASSWORD=password
      - TZ=GMT
    ports:
      - 5432:5432
    volumes:
      - ./test-data.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
